name: snaply
description: "Elke dag een nieuwe foto-opdracht!"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  get_it: ^9.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  build_runner: ^2.9.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
